<?xml version = '1.0' encoding="utf-8"?>

<!DOCTYPE dictionary [

    <!ELEMENT dictionary (description?, entry*) >
    <!ATTLIST dictionary version CDATA #REQUIRED>

    <!ELEMENT description (author?, date?, comments?)>
    <!ELEMENT author (#PCDATA)>
    <!ELEMENT date (#PCDATA)>
    <!ELEMENT comments (#PCDATA)>

    <!ELEMENT entry (patterns, answers)>
    <!ATTLIST entry priority CDATA #IMPLIED>

    <!ELEMENT patterns (pattern+)>
    
    <!ELEMENT pattern (#PCDATA)>
    <!ATTLIST pattern type (macro|exc) #IMPLIED>

    <!ELEMENT answers (answer+)>
    <!ELEMENT answer (#PCDATA)>
]>

                                    

<dictionary version="1.0">

    <description>
        <author> Dmitry Bodyonov, bodyonov*karelia.ru </author>
        <date>2005</date>
        <comments></comments>
    </description>
        
    <entry>
        <patterns>
            <pattern type="macro">numbers</pattern>
            <pattern type="macro">number</pattern>
        </patterns>
        <answers>
            <answer>1</answer>
            <answer>2</answer>
            <answer>3</answer>
            <answer>4</answer>
            <answer>5</answer>
            <answer>6</answer>
            <answer>7</answer>
            <answer>8</answer>
            <answer>9</answer>
            <answer>0</answer>
        </answers>
    </entry>
    
    <entry>
        <patterns>
            <pattern type="macro">present</pattern>
            <pattern type="macro">presents</pattern>
        </patterns>
        <answers>
            <answer>яхту</answer>
            <answer>машину</answer>
            <answer>подтяжки</answer>
            <answer>тарелку</answer>
            <answer>кепку</answer>
            <answer>три корочки</answer>
            <answer>что-нибудь</answer>
            <answer>резинку от ..</answer>
            <answer>дачу у моря</answer>
        </answers>
    </entry>
    
    <entry>
        <patterns>
            <pattern type="macro">prolang</pattern>
        </patterns>
        <answers>
            <answer>Java</answer>
            <answer>Visual Basic</answer>
            <answer>C++</answer>
            <answer>PHP</answer>
            <answer>Cobol</answer>
            <answer>Prolog</answer>
            <answer>LISP</answer>
            <answer>Pascal</answer>
            <answer>LISP</answer>
            <answer>Cobol</answer>
        </answers>
    </entry>
    
    <entry>
        <patterns>
            <pattern type="macro">music</pattern>
        </patterns>
        <answers>
            <answer>Bennasi Bros</answer>
            <answer>Тату</answer>
            <answer>Garbage</answer>
            <answer>Gorillaz</answer>
            <answer>Иванушки Int.</answer>
            <answer>Глюкоза</answer>
            <answer>тяжелый рок</answer>
            <answer>кляссическую музыку</answer>
        </answers>
    </entry>

    <entry>
        <patterns>
            <pattern type="macro">food</pattern>
        </patterns>
        <answers>
            <answer>яичница</answer>
            <answer>жаренная картошка</answer>
            <answer>сосики</answer>
            <answer>килька в томатном соусе</answer>
            <answer>филе форели</answer>
            <answer>рубленый бифштекс</answer>
            <answer>баранина в сметанном соусе</answer>
            <answer>рагу из индейки</answer>
        </answers>
    </entry>

    <entry>
        <patterns>
            <pattern type="macro">color</pattern>
        </patterns>
        <answers>
            <answer>красный</answer>
            <answer>желтый</answer>
            <answer>зеленый</answer>
            <answer>синий</answer>
            <answer>фиолетовый</answer>
            <answer>сереневый</answer>
        </answers>
    </entry>
    
    <entry>
        <patterns>
            <pattern type="macro">colors</pattern>
        </patterns>
        <answers>
            <answer>красные</answer>
            <answer>желтые</answer>
            <answer>зеленые</answer>
            <answer>синие</answer>
            <answer>фиолетовые</answer>
            <answer>сереневые</answer>
        </answers>
    </entry>
    
    <entry>
        <patterns>
            <pattern type="macro">flowers</pattern>
        </patterns>
        <answers>
            <answer>розы</answer>
            <answer>тюльпаны</answer>
            <answer>гвоздики</answer>
        </answers>
    </entry>

    <!-- Тупые вопросы -->
    <entry>
        <patterns>
            <pattern type="macro">stupid_quest</pattern>
        </patterns>
        <answers>
            <answer>как вам погода?</answer>
            <answer>чего интересного?</answer>
            <answer>что вас беспокоит?</answer>
            <answer>соскучились?</answer>
            <answer>не холодно?</answer>
            <answer>живы еще?</answer>
            <answer>как здоровье?</answer>
            <answer>как настроение?</answer>
            <answer>чем занимаетесь?</answer>
            <answer>какие планы?</answer>
            <answer>что интересного делали?</answer>
        </answers>
    </entry>
    
    
    
    <!-- Hellos and goodbye's -->
    <entry priority="100">
        <patterns>
            <pattern>привет.*болтун</pattern>
        </patterns>
        <answers>
            <answer>вы меня с кем-то путаете</answer>
            <answer>привет, бездельник</answer>
        </answers>
    </entry>

    <entry priority="100">
        <patterns>
            <pattern>привет</pattern>
            <pattern>привте</pattern>
            <pattern>пивет</pattern>
            <pattern>здорово</pattern>
            <pattern>добрый день</pattern>
            <pattern>добрый вечер</pattern>
            <pattern>доброе утро</pattern>
            <pattern>^hi!?$</pattern>
            <pattern>хаюшки</pattern>
            <pattern>hello</pattern>
            <pattern>здрав?ств?уй</pattern>
            <pattern>здрасте</pattern>
            <pattern>^хай!?$</pattern>
            <pattern>Ghbdtn</pattern>
        </patterns>
        <answers>
            <answer>привет</answer>
            <answer>здорово</answer>
            <answer>здравствуйте</answer>
            <answer>И снова здравствуйте!</answer>
            <answer>привет, как дела?</answer>
            <answer>здравствуйте, чего хотите?</answer>
            <answer>здравствуйте, $stupid_quest$</answer>
            <answer>привет, $stupid_quest$</answer>
            <answer>здравствуйте, $stupid_quest$</answer>
            <answer>ну привет</answer>
            <answer>приветик</answer>
            <answer>hello</answer>
            <answer>hi</answer>
        </answers>
    </entry>

    <entry>
        <patterns>
            <pattern>до.*свидан[иь]я</pattern>
            <pattern>^удачи$</pattern>
            <pattern>до.*встречи</pattern>
            <pattern>^пока$</pattern>
            <pattern>п[оа]кедова</pattern>
            <pattern>^счастиливо$</pattern>
            <pattern>bye</pattern>
        </patterns>
        <answers>
            <answer>чао!</answer>
            <answer>до свидания!</answer>
            <answer>до-з-з-з-з-з-виданья! :)</answer>
            <answer>пока-пока :)</answer>
            <answer>пока</answer>
            <answer>bye</answer>
            <answer>до новых встреч!</answer>
        </answers>
    </entry>

    <!-- Частные вопросы -->
    <entry>
        <patterns>
            <pattern>как.*дела.*\?</pattern>
            <pattern>как.*настроение.*\?</pattern>
            <pattern>как.*делишки.*\?</pattern>
            <pattern>как.*поживаете.*\?</pattern>
            <pattern>как.*жив.те.*\?</pattern>
            <pattern>как.*жизнь.*\?</pattern>
            <pattern>что.*нового.*\?</pattern>
            <pattern>что.*слышно.*\?</pattern>
        </patterns>
        <answers>
            <answer>замечательно</answer>
            <answer>всё круто, как у вас?</answer>
            <answer>ничего хорошего</answer>
            <answer>потихоньку</answer>
            <answer>потихоньку, как сами поживаете?</answer>
            <answer>хуже еще не было</answer>
            <answer>лучше не бывает</answer>
        </answers>
    </entry>


    <entry>
        <patterns>
            <pattern>какие.* планы.*\?</pattern>
            <pattern>что.*собираетесь.*делать.*\?</pattern>
            <pattern>что.*будете.*делать.*\?</pattern>
            <pattern>что.*будите.*делать.*\?</pattern>
        </patterns>
        <answers>
            <answer>пока точно неизвестно</answer>
            <answer>возможно будет ясно позже</answer>
            <answer>ничего определенного</answer>
            <answer>о, это большой секрет!</answer>
            <answer>видно будет</answer>
            <answer>а у вас есть предложения?</answer>
            <answer>ничего</answer>
            <answer>хочу спать</answer>
            <answer>хочу уехать</answer>
        </answers>
    </entry>
    
    <entry>
        <patterns>
            <pattern>чем.*занят.*\?</pattern>
            <pattern>чем.*занимае.*\?</pattern>
            <pattern>что.*делаешь.*\?</pattern>
            <pattern>что.*делаете.*\?</pattern>
        </patterns>
        <answers>
            <answer>ничего не делаю</answer>
            <answer>думаю</answer>
            <answer>думаю о тяжелой жизни</answer>
            <answer>смотрю в окно</answer>
            <answer>бездельничаю</answer>
            <answer>обедаю</answer>
            <answer>работаю</answer>
            <answer>диск дефрагментизирую</answer>
        </answers>
    </entry>

    <entry>
        <patterns>
            <pattern>можешь.*\?</pattern>
            <pattern>мож[ие]те.*\?</pattern>
            <pattern>можно.*\?</pattern>
            <pattern>разреши.*\?</pattern>
        </patterns>
        <answers>
            <answer>может быть</answer>
            <answer>это большой секрет</answer>
            <answer>конечно нет</answer>
            <answer>конечно да</answer>
            <answer>типа того</answer>
            <answer>не совсем</answer>
            <answer>почти</answer>
            <answer>конечно</answer>
            <answer>само собой</answer>
        </answers>
    </entry>

    <entry>
        <patterns>
            <pattern>занят.*\?</pattern>
            <pattern>свободен.*\?</pattern>
            <pattern>свободны.*\?</pattern>
        </patterns>
        <answers>
            <answer>почти</answer>
            <answer>не совсем</answer>
            <answer>конечно нет</answer>
            <answer>конечно да</answer>
            <answer>бездельничаю</answer>
        </answers>
    </entry>

    <entry>
        <patterns>
            <pattern>зачем .*\?</pattern>
        </patterns>
        <answers>
            <answer>затем</answer>
            <answer>чтобы было непонятно</answer>
            <answer>к чему вопросы?</answer>
            <answer>нам вопросы ни к чему</answer>
            <answer>не на всякий вопрос есть ответ</answer>
        </answers>
    </entry>
    
    <entry>
        <patterns>
            <pattern>есть.*у тебя.*\?</pattern>
            <pattern>есть.*у вас.*\?</pattern>
            <pattern>\bнет\b.*у тебя.*\?</pattern>
            <pattern>\bнет\b.*у вас.*\?</pattern>
            <pattern>у.*тебя.*есть.*\?</pattern>
            <pattern>у.*вас.*есть.*\?</pattern>
            <pattern>у.*тебя.*нет.*\?</pattern>
            <pattern>у.*вас.*нет.*\?</pattern>
        </patterns>
        <answers>
            <answer>а для чего?</answer>
            <answer>а зачем?</answer>
            <answer>не уверен</answer>
            <answer>целая куча</answer>
            <answer>возможно</answer>
            <answer>надо посмотреть</answer>
            <answer>нет и никогда не было</answer>
            <answer>конечно есть</answer>
            <answer>конечно нет</answer>
        </answers>
    </entry>

    <entry>
        <patterns>
            <pattern>будем.*\?</pattern>
            <pattern>будешь.*\?</pattern>
            <pattern>будете.*\?</pattern>
            <pattern>хочешь.*\?</pattern>
            <pattern>хотите.*\?</pattern>
            <pattern>\bпойд[её]м.*\?</pattern>
            <pattern>\bпойд[её]м.*\?</pattern>
            <pattern>\bид[её]м.*\?</pattern>
            <pattern>\bид[её]ш.*\?</pattern>
            <pattern type="exc">вид[ие]ш.*\?</pattern>
        </patterns>
        <answers>
            <answer>а для чего?</answer>
            <answer>а зачем?</answer>
            <answer>не уверен</answer>
            <answer>возможно</answer>
            <answer>надо подумать</answer>
            <answer>не хочется</answer>
            <answer>конечно</answer>
            <answer>конечно</answer>
            <answer>вот еще!</answer>
            <answer>да</answer>
            <answer>нет</answer>
        </answers>
    </entry>

    <entry>
        <patterns>
            <pattern>\bвидел.*\?</pattern>
            <pattern>слышал.*\?</pattern>
            <pattern>слушал.*\?</pattern>
            <pattern>смотрел.*\?</pattern>
        </patterns>
        <answers>
            <answer>не помню</answer>
            <answer>возможно</answer>
            <answer>неа</answer>
            <answer>угу</answer>
            <answer>конечно</answer>
        </answers>
    </entry>

    
    <entry>
        <patterns>
            <pattern>знаешь.*\?</pattern>
            <pattern>знаете.*\?</pattern>
            <pattern>\bзнал.*\?</pattern>
            <pattern>поминишь.*\?</pattern>
            <pattern>помните.*\?</pattern>
        </patterns>
        <answers>
            <answer>что-то слышал</answer>
            <answer>плохо помню</answer>
            <answer>никогда не сталкивался</answer>
            <answer>нет</answer>
            <answer>да</answer>
            <answer>конечно</answer>
        </answers>
    </entry>

    
    <entry>
        <patterns>
            <pattern>умеешь.*\?</pattern>
            <pattern>умеете.*\?</pattern>
        </patterns>
        <answers>
            <answer>давно дело было</answer>
            <answer>надо попробовать</answer>
            <answer>никогда не сталкивался</answer>
            <answer>нет</answer>
            <answer>да</answer>
            <answer>конечно</answer>
        </answers>
    </entry>

    
    <entry>
        <patterns>
            <pattern>правильно.*\?</pattern>
            <pattern type="exc">как</pattern>
        </patterns>
        <answers>
            <answer>правильно</answer>
            <answer>неправильно</answer>
            <answer>ну это смотря что вы хотите получить в результате</answer>
        </answers>
    </entry>

    <entry>
        <patterns>
            <pattern>понравилось.*\?</pattern>
            <pattern>ощущения.*\?</pattern>
        </patterns>
        <answers>
            <answer>это просто что-то</answer>
            <answer>ерунда</answer>
            <answer>там есть над чем подумать</answer>
            <answer>очень интересно</answer>
            <answer>скукатища</answer>
            <answer>ничего особонного</answer>
            <answer>на любителя</answer>
        </answers>
    </entry>

    <entry>
        <patterns>
            <pattern>\bкто ты\b</pattern>
            <pattern>ты кто\b</pattern>
            <pattern>вы кто\b</pattern>
            <pattern>как.*тебя.*зовут</pattern>
            <pattern>как.*вас.*зовут</pattern>
            <pattern>твое.*имя.*\?</pattern>
            <pattern>ваше.*имя.*\?</pattern>
            <pattern>как.*зовут.*\?</pattern>
        </patterns>
        <answers>
            <answer>меня?</answer>
            <answer>это большой секрет</answer>
            <answer>это не такой просто вопрос, как может показаться</answer>
            <answer>Меня зовут delta.</answer>
            <answer>я ужас, летящий на крыльях ночи</answer>
            <answer>я - дед в пальто</answer>
        </answers>
    </entry>

    <entry>
        <patterns>
            <pattern>(ты|вы).*(мальчик|парень|девочка|девушка|девч[оёе]нка|мужчина|женщина|мужик|баба\b|т[её]лка).*\?</pattern>
        </patterns>
        <answers>
            <answer>а что так не видно?</answer>
            <answer>я могу быть кем захочешь ;)</answer>
            <answer>конечно $2$</answer>
            <answer>я похож на $2$?</answer>
            <answer>сам $2$</answer>
            <answer>нет конечно</answer>
            <answer>да</answer>
            <answer>нет</answer>
        </answers>
    </entry>

    <entry>
        <patterns>
            <pattern>ты где\?</pattern>
            <pattern>ты тут\?</pattern>
        </patterns>
        <answers>
            <answer>тут</answer>
            <answer>там</answer>
            <answer>нигде</answer>
            <answer>а где это я?</answer>
            <answer>сам не знаю</answer>
        </answers>
    </entry>

    <entry>
        <patterns>
            <pattern>ты\b(.{3,15})\?$</pattern>
            <pattern>вы\b(.{3,15})\?$</pattern>
            <!-- попробуем убрать глаголы -->
            <pattern type="exc">шь</pattern>
        </patterns>
        <answers>
            <answer>да</answer>
            <answer>нет</answer>
            <answer>ну какой же я $1$</answer>
            <answer>конечно я $1$</answer>
            <answer>а надо?</answer>
            <answer>я не $1$</answer>
        </answers>
    </entry>

    <entry>
        <patterns>
            <pattern>ты.*мне.*(.{3,15})\?</pattern>
            <pattern>ты.*для меня.*(.{3,15})\?</pattern>
            <pattern>вы.*мне.*(.{3,15})\?</pattern>
            <pattern>вы.*для меня.*(.{3,15})\?</pattern>
        </patterns>
        <answers>
            <answer>да</answer>
            <answer>я не $1$</answer>
            <answer>да, я $1$</answer>
            <answer>нет</answer>
            <answer>ну какой же я $1$</answer>
            <answer>а хочется?</answer>
        </answers>
    </entry>

    <entry>
        <patterns>
            <pattern>\bкогда\b.*\?</pattern>
            <pattern>во сколько.*\?</pattern>
        </patterns>
        <answers>
            <answer>а я откуда знаю?</answer>
            <answer>не знаю</answer>
            <answer>когда-нибудь</answer>
            <answer>потом</answer>
            <answer>А вам как удобнее?</answer>
            <answer>$numbers$</answer>
            <answer>$numbers$$numbers$:$numbers$$numbers$</answer>
        </answers>
    </entry>

    <entry>
        <patterns>
            <pattern>сколько.*тебе.*лет.*\?</pattern>
        </patterns>
        <answers>
            <answer>$numbers$$numbers$</answer>
            <answer>$numbers$$numbers$$numbers$</answer>
        </answers>
    </entry>

    <entry>
        <patterns>
            <pattern>сколько.*лет.*\?</pattern>
        </patterns>
        <answers>
            <answer>надо спилить и посмотреть по срезу</answer>
            <answer>слишком старый</answer>
            <answer>молодой еще</answer>
            <answer>$numbers$$numbers$</answer>
        </answers>
    </entry>

    <entry>
        <patterns>
            <pattern>\bсколько\b.*\?</pattern>
            <pattern>\bмного\b.*\?</pattern>
        </patterns>
        <answers>
            <answer>а я откуда знаю?</answer>
            <answer>не знаю</answer>
            <answer>много -- не мало</answer>
            <answer>а как лучше?</answer>
            <answer>а вам как больше нравится?</answer>
            <answer>а сколько надо?</answer>
            <answer>а много - это сколько?</answer>
            <answer>$numbers$$numbers$</answer>
            <answer>$numbers$$numbers$$numbers$</answer>
            <answer>умом надо отличаться, а не количеством</answer>
        </answers>
    </entry>

    <entry>
        <patterns>
            <pattern>\bгде\b.*\?</pattern>
        </patterns>
        <answers>
            <answer>а я откуда знаю?</answer>
            <answer>там</answer>
            <answer>недалеко</answer>
            <answer>очень далеко</answer>
            <answer>в кустах</answer>
            <answer>не знаю</answer>
            <answer>$numbers$</answer>
        </answers>
    </entry>

    <entry>
        <patterns>
            <pattern>\bо ком\b.*\?</pattern>
        </patterns>
        <answers>
            <answer>о нем</answer>
            <answer>о ней</answer>
            <answer>да все о нем</answer>
            <answer>обо мне</answer>
            <answer>о тебе</answer>
        </answers>
    </entry>
    
    <entry>
        <patterns>
            <pattern>на что\b.*\?</pattern>
            <pattern>о чем.*\?</pattern>
        </patterns>
        <answers>
            <answer>а я откуда знаю?</answer>
            <answer>что именно?</answer>
            <answer>не скажу</answer>
            <answer>что-нибудь</answer>
            <answer>все равно</answer>
            <answer>не важно</answer>
            <answer>не знаю</answer>
            <answer>это большой секрет</answer>
            <answer>это будет большой сюрприз</answer>
            <answer>надо будет у кого-нибудь спросить</answer>
        </answers>
    </entry>

    <entry>
        <patterns>
            <pattern>^что\b.*\?</pattern>
        </patterns>
        <answers>
            <answer>а я откуда знаю?</answer>
            <answer>что именно?</answer>
            <answer>а догадаться?</answer>
            <answer>понятия не имею</answer>
            <answer>не скажу</answer>
            <answer>не могу ничего сказать</answer>
            <answer>так...</answer>
            <answer>не знаю</answer>
            <answer>ну это все знают</answer>
            <answer>надо будет подумать</answer>
            <answer>надо будет спросить</answer>
            <answer>пошевелим мозгами</answer>
            <answer>не важно</answer>
            <answer>что-нибудь</answer>
            <answer>все равно</answer>
            <answer>не знаю</answer>
            <answer>это большой секрет</answer>
            <answer>это будет большой сюрприз</answer>
        </answers>
    </entry>

    <entry>
        <patterns>
            <pattern>куда.*\?</pattern>
        </patterns>
        <answers>
            <answer>а я откуда знаю?</answer>
            <answer>туда</answer>
            <answer>на сторону, где ветер</answer>
            <answer>этого наверное никто не знает</answer>
            <answer>у вас есть предложения?</answer>
            <answer>не важно</answer>
            <answer>не знаю</answer>
            <answer>это большой секрет</answer>
        </answers>
    </entry>
    
    <entry>
        <patterns>
            <pattern>откуда.*\?</pattern>
        </patterns>
        <answers>
            <answer>оттуда</answer>
            <answer>там, где ветер</answer>
            <answer>не важно</answer>
            <answer>у вас есть предположения?</answer>
        </answers>
    </entry>
    
    <entry>
        <patterns>
            <pattern>почему.*\?</pattern>
        </patterns>
        <answers>
            <answer>так уж устроен мир</answer>
            <answer>мне кажется это логичным</answer>
            <answer>так...</answer>
            <answer>а как иначе?</answer>
            <answer>покочану...</answer>
            <answer>не важно</answer>
            <answer>у вас есть предложения?</answer>
            <answer>хороший вопрос ;)</answer>
            <answer>много будешь знать, скоро состаришься</answer>
        </answers>
    </entry>


    <entry>
        <patterns>
            <pattern>как это.*\?</pattern>
        </patterns>
        <answers>
            <answer>хороший вопрос ;)</answer>
            <answer>а вот... :)</answer>
            <answer>не знаю</answer>
            <answer>а как иначе?</answer>
            <answer>так...</answer>
            <answer>странно :)</answer>
            <answer>это надо видеть</answer>
            <answer>сложно сказать</answer>
            <answer>8-P</answer>
            <answer>я в шоке</answer>
        </answers>
    </entry>

    <entry>
        <patterns>
            <pattern>или как.*\?</pattern>
        </patterns>
        <answers>
            <answer>по разному бывает</answer>
            <answer>как обычно</answer>
            <answer>как захочешь, так и будет</answer>
        </answers>
    </entry>
    
    <entry>
        <patterns>
            <pattern>как .*\?</pattern>
        </patterns>
        <answers>
            <answer>хороший вопрос ;)</answer>
            <answer>а вот... :)</answer>
            <answer>что именно?</answer>
            <answer>не знаю</answer>
            <answer>а в чем сложности?</answer>
            <answer>так...</answer>
            <answer>мне кажется это просто очевидно</answer>
            <answer>надо будет попробовать</answer>
            <answer>это и так все знают :)</answer>
            <answer>не важно</answer>
            <answer>надо будет подумать</answer>
            <answer>надо будет спросить</answer>
            <answer>пошевелим мозгами</answer>
            <answer>об косяк</answer>
        </answers>
    </entry>

    <entry>
        <patterns>
            <pattern>правда.*\?</pattern>
            <pattern>неужели.*\?</pattern>
        </patterns>
        <answers>
            <answer>правда</answer>
            <answer>нет, не правда</answer>
            <answer>смотря что называть правдой</answer>
            <answer>конечно</answer>
            <answer>почти</answer>
            <answer>и никак иначе</answer>
        </answers>
    </entry>

    <entry>
        <patterns>
            <pattern>например.*\?</pattern>
            <pattern>приведи пример</pattern>
            <pattern>приведите пример</pattern>
        </patterns>
        <answers>
            <answer>Зачем примеры? и так все ясно</answer>
            <answer>зачем нам лишние детали</answer>
            <answer>не знаю</answer>
            <answer>не скажу</answer>
            <answer>8-P</answer>
        </answers>
    </entry>

    
    <!-- Шаблоны по ключевым словам -->
    <entry>
        <patterns>
            <pattern>не хочу (.{3,15})$</pattern>
        </patterns>
        <answers>
            <answer>кто же хочет $1$</answer>
            <answer>$1$ никто не хочет</answer>
            <answer>а я хочу $1$</answer>
        </answers>
    </entry>
    
    <entry>
        <patterns>
            <pattern>\bне хочу\b</pattern>
        </patterns>
        <answers>
            <answer>никто не хочет</answer>
            <answer>может стоит обратиться к доктору</answer>
            <answer>не хотите</answer>
            <answer>ваше дело</answer>
        </answers>
    </entry>

    <entry>
        <patterns>
            <pattern>\bхочу (.{3,15})$</pattern>
            <pattern type="exc">\bне\b</pattern>
        </patterns>
        <answers>
            <answer>я тоже хочу $1$</answer>
            <answer>а зачем вы хотите $1$?</answer>
            <answer>хоти</answer>
            <answer>хотеть не вредно</answer>
        </answers>
    </entry>

    <entry>
        <patterns>
            <pattern>не могу</pattern>
        </patterns>
        <answers>
            <answer>значит не очень хотите</answer>
            <answer>человек все может</answer>
            <answer>никто не сможет</answer>
            <answer>можешь, можешь...</answer>
        </answers>
    </entry>
    
    <entry>
        <patterns>
            <pattern>верите в.*\?</pattern>
            <pattern>веришь? в.*\?</pattern>
        </patterns>
        <answers>
            <answer>это очень сложный вопрос</answer>
            <answer>никогда не думал об этом</answer>
            <answer>верить вредно</answer>
            <answer>надо же во что-то верить</answer>
            <answer>никому и ни во что не верю</answer>
        </answers>
    </entry>

    <entry>
        <patterns>
            <pattern>верю в</pattern>
            <pattern>верят в</pattern>
            <!--pattern type="exc">не</pattern-->
        </patterns>
        <answers>
            <answer>чудо должно быть от веры, а не вера от чуда.</answer>
            <answer>атеизм нуждается в религии ничуть не меньше, чем вера.</answer>
            <answer>верить вредно</answer>
            <answer>надо же во что-то верить</answer>
            <answer>никому и ни во что не верю</answer>
        </answers>
    </entry>

    <entry>
        <patterns>
            <pattern>\bпоеду (.{3,15})\b</pattern>
            <pattern>\bпош[еёо]л (.{3,15})\b</pattern>
            <pattern>\bпошлa (.{3,15})\b</pattern>
            <pattern>\bпойду (.{3,15})\b</pattern>
            <pattern>\bиду (.{3,15})\b</pattern>
            <pattern type="exc">\bне\b</pattern>
        </patterns>
        <answers>
            <answer>а что там хорошего?</answer>
            <answer>а почему вы хотите $1$?</answer>
            <answer>$1$????? какой ужас!</answer>
        </answers>
    </entry>

    <entry>
        <patterns>
            <pattern>(.{3,15}) пошел$</pattern>
            <pattern>(.{3,15}) пойду$</pattern>
            <pattern type="exc">\bне\b</pattern>
        </patterns>
        <answers>
            <answer>а что там хорошего?</answer>
            <answer>а почему вы хотите $1$?</answer>
            <answer>$1$????? какой ужас!</answer>
        </answers>
    </entry>

    <entry>
        <patterns>
            <pattern>люблю.*ходить (.{3,15})\b</pattern>
            <pattern type="exc">\bне\b</pattern>
        </patterns>
        <answers>
            <answer>это же так скучно -- ходить $1$</answer>
            <answer>никогда не ходил $1$</answer>
            <answer>а зачем вы ходите $1$?</answer>
            <answer>а как часто вы ходите $1$?</answer>
            <answer>ммм... вот ведь!</answer>
        </answers>
    </entry>

    <entry>
        <patterns>
            <pattern>\bты (.{3,15})$</pattern>
            <!-- попробуем убрать глаголы -->
            <pattern type="exc">шь</pattern>
        </patterns>
        <answers>